test:
  adapter: postgresql
  database: hypersleep_test
  usename: postgres

development:
  adapter: postgresql
  database: hypersleep_development
  usename: postgres

production:
  adapter: postgresql
  database: hypersleep_production
  usename: postgres
